language: node_js

node_js:
  - "node"
  - "lts/*"
  
stages:
  - lint
  - test
  - deploy
jobs:
  include:
    - stage: lint
    script: echo "lint"
    - stage: test
    script: echo "teste"
    - stage: deploy
    script: echo "deploy"
