language: node_js
node_js:
- lts/*
stages:
- lint
- test
- deploy
jobs:
  include:
  - stage: lint
    script:
    - npm run lint
  - stage: test
    script:
    - npm run test
  - stage: deploy
    script: echo "Publishing to npm..."
    deploy:
      provider: npm
      on:
        branch: master
      email:
        secure: NQpom+f/qWYtz+Vag+dj4FEGrfuToaR2/hiVIMy99nwjoaVr5VNYy04v5XZvceGxvdtmNMcvgsA1DBQI8RfIydWv+N/2k1oCitNOrmtNvzFucE54ywFcYqYp2sYk6dTA2SZNpoLdwT3szDcXyOi4k0+WN6AUxmzWz2Y4HRAxVeaY6aEudevNh+xteUeRs/Pr1zBxPI0uUQoJedamqT1k3xEZAujJjZRhmONDCxhR5qY9SIhHi6LgW+/msyoerqbrdCRogcpILfJFtKSr4iicKMQBuH7+P827zAzomLr3JfBfjh+rnbUaYS4/8MBmEXKQesgHFNo01LaX0/ztAhKH56RmCbAom0NI55+ZvAz0z0wnPfXM2diQqaSxA6ZWl836DKPWeY2C6jgwIqUj4a78q+pjJ22en8jFfT3uWH5SoijnXRli5BuX+30zlokrMuN94vEtgoXI6KF1rHWvSRYabwBlnq5QcU66dLs/caSDg2+KD+WzbozHo/pnojhnUXThMPom9cz9MY2gF15pwJLTprgVNu5Og3bYrY+1qHWA8p5rScUtQjNcR/V7HjdsuVzWgJ/oEaN6OMVjQqLwT3/bWznnKecyxc6INEwFkgcIxvw9Ef4wkNB6vxleX0ee7QBNqobSgTP/sDW+pK611P/0pgOv4uQAc7dCL/76glY6c4g=
      api_key:
        secure: 024NXSe86Dl+gb3KuiIQJ8jiLe/hcyTMS9AYH6qb8kSWaMTfCN5+1wzplG7ThaabFnTVLvfHZdCA9qz+kSlUDaTJCcqMNB7x+y39qOjOtzpa9/X3sWkVDjqSkgnLNaOrNSLVnavoxdzZZOGYJQGueQjiNwNGCkhBNbQBZgaWtb2H2nQcOYaaJzaydgkWaBRQs01nwcQK0U951Tx4n4l1fjjLbVcEpCBgRGql6y8Rb4/0LCFtBztWiBadMGNLT82cjlGex6HzPnaaMAiDSdfpt9WHdwgtgtwt6kYOmeGxopyJLtX1oobji138YGL48R1xJe7YWxaA5psLyQCI7e4OAav+dQbcNPoN1jgWwIkz+dvOOG/1ob7XtwJ82w+fBmYAL7YPbHnaVnY+HGOcqJWy/88Cal3u8XEJLWZWThVHgtt1RlFnxj8WiVljBjUb39z2Co34miqxbzYB35Il6YROEdngBnRAF1niFYlkDQDUmugOa8wcX27cz9Szv1FlAMK6oImuJSSqiDdfj6IgQkUntzeAmbih04Vg0UnGG+x0RXo+7kKp3OBDzsiCRC5T68Fjzm80yM3mQbZjH14l0bFu8Meudm0HNGExgB9Xy6dX4px0G3yJhtvQhauTDax9FDw8OXM1pwUF39lAm2sPbbgV20NSRo0W959Mx0zGIpedlao=
      skip_cleanup: true
